/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseSVG: typeof import('./components/base/BaseSVG.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillDamageIcon: typeof import('./components/skill/SkillDamageIcon.vue')['default']
    SkillItem: typeof import('./components/skill/SkillItem.vue')['default']
    SkillItemModifier: typeof import('./components/skill/SkillItemModifier.vue')['default']
    SkillLine: typeof import('./components/skill/SkillLine.vue')['default']
    SkillTier: typeof import('./components/skill/tier/SkillTier.vue')['default']
    SkillTierNode: typeof import('./components/skill/tier/SkillTierNode.vue')['default']
    SkillTierSpikes: typeof import('./components/skill/tier/SkillTierSpikes.vue')['default']
    SkillTooltip: typeof import('./components/skill/SkillTooltip.vue')['default']
    SkillTree: typeof import('./components/skill/tree/SkillTree.vue')['default']
  }
}
